package bundle

import (
	"archive/zip"
	"encoding/binary"
	"encoding/json"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const testSHA = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

func writeTestFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func writeLauncherFixture(t *testing.T, filename, target string) {
	t.Helper()
	header := make([]byte, 128)
	switch target {
	case "windows-amd64":
		copy(header[:2], "MZ")
		binary.LittleEndian.PutUint32(header[0x3c:0x40], 0x40)
		copy(header[0x40:0x44], "PE\x00\x00")
		binary.LittleEndian.PutUint16(header[0x44:0x46], 0x8664)
	case "macos-amd64":
		copy(header[:4], []byte{0xcf, 0xfa, 0xed, 0xfe})
		binary.LittleEndian.PutUint32(header[4:8], 0x01000007)
	case "macos-arm64":
		copy(header[:4], []byte{0xcf, 0xfa, 0xed, 0xfe})
		binary.LittleEndian.PutUint32(header[4:8], 0x0100000c)
	case "linux-amd64":
		copy(header[:4], "\x7fELF")
		header[4], header[5] = 2, 1
		binary.LittleEndian.PutUint16(header[18:20], 0x3e)
	case "linux-arm64":
		copy(header[:4], "\x7fELF")
		header[4], header[5] = 2, 1
		binary.LittleEndian.PutUint16(header[18:20], 0xb7)
	default:
		t.Fatalf("unknown launcher fixture target %q", target)
	}
	if err := os.MkdirAll(filepath.Dir(filename), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filename, header, 0o755); err != nil {
		t.Fatal(err)
	}
}

func writeTestJSON(t *testing.T, path string, value any) {
	t.Helper()
	content, err := json.Marshal(value)
	if err != nil {
		t.Fatal(err)
	}
	writeTestFile(t, path, string(content))
}

func testArtifact(t *testing.T) string {
	t.Helper()
	root := filepath.Join(t.TempDir(), "Pages artifact with spaces")
	identity := map[string]any{
		"package": map[string]any{
			"name": "OpenSpecy", "version": "1.7.1", "commit": testSHA,
		},
	}
	app := map[string]any{
		"package": identity["package"],
		"wasm_build": map[string]any{
			"artifact": "openspecy-wasm-" + testSHA,
			"immutable": true, "bundled_into_app": true,
		},
	}
	writeTestJSON(t, filepath.Join(root, "_wasm", "wasm-app-manifest.json"), app)
	writeTestJSON(t, filepath.Join(root, "_wasm", "pinned", "metadata",
		"resolved-wasm-packages.json"), identity)
	writeTestJSON(t, filepath.Join(root, "_site", "app",
		"pinned-wasm-library.json"), identity)
	writeTestFile(t, filepath.Join(root, "_site", "index.html"),
		"<main data-openspecy-embed>landing</main>")
	writeTestFile(t, filepath.Join(root, "_site", "app", "index.html"),
		"<script>runExportedApp()</script>")
	writeTestFile(t, filepath.Join(root, "_site", "pkgdown", "index.html"),
		"<!-- Generated by pkgdown -->")
	writeTestFile(t, filepath.Join(root, "_site", "app", "shinylive", "shinylive.js"),
		"shinylive bundle")
	writeTestFile(t, filepath.Join(root, "_site", "app", "shinylive", "webr",
		"packages", "metadata.rds"), "metadata")
	writeTestFile(t, filepath.Join(root, "_site", "app", "shinylive", "webr",
		"packages", "OpenSpecyPinned", "library.data.gz"), "library image")
	writeTestFile(t, filepath.Join(root, "_site", "app", "shinylive", "webr",
		"packages", "OpenSpecyPinned", "library.js.metadata"), "library metadata")
	writeTestFile(t, filepath.Join(root, "_site", "app", "exact bytes.bin"),
		"\x00\x01 exact site bytes")
	return root
}

func readArchiveEntry(t *testing.T, archivePath, entryName string) ([]byte, os.FileMode) {
	t.Helper()
	reader, err := zip.OpenReader(archivePath)
	if err != nil {
		t.Fatal(err)
	}
	defer reader.Close()
	for _, entry := range reader.File {
		if entry.Name != entryName {
			continue
		}
		file, err := entry.Open()
		if err != nil {
			t.Fatal(err)
		}
		content, err := io.ReadAll(file)
		file.Close()
		if err != nil {
			t.Fatal(err)
		}
		return content, entry.Mode()
	}
	t.Fatalf("archive entry %q not found", entryName)
	return nil, 0
}

func TestBuildCreatesExactOfflineArchive(t *testing.T) {
	artifact := testArtifact(t)
	launcher := filepath.Join(t.TempDir(), "launcher")
	writeLauncherFixture(t, launcher, "linux-amd64")
	output := filepath.Join(t.TempDir(),
		"openspecy-offline-linux-amd64-"+testSHA+".zip")
	result, err := Build(Config{
		ArtifactRoot: artifact,
		Launcher: launcher,
		Output: output,
		PackageSHA: testSHA,
		Target: "linux-amd64",
		SourceRepository: "example/OpenSpecy-package",
		SourceRunID: "12345",
	})
	if err != nil {
		t.Fatal(err)
	}
	if result.FileCount < 8 || result.SiteBytes == 0 || len(result.ArchiveSHA256) != 64 {
		t.Fatalf("unexpected build result %#v", result)
	}
	if _, err := os.Stat(output + ".sha256"); err != nil {
		t.Fatal(err)
	}
	if err := verifyArchiveCompanion(output); err != nil {
		t.Fatalf("valid checksum companion was rejected: %v", err)
	}
	root := "OpenSpecy-offline-" + testSHA + "/"
	content, _ := readArchiveEntry(t, output, root+"site/app/exact bytes.bin")
	if string(content) != "\x00\x01 exact site bytes" {
		t.Fatalf("site bytes changed: %q", content)
	}
	_, mode := readArchiveEntry(t, output, root+"OpenSpecy Offline")
	if mode.Perm()&0o111 == 0 {
		t.Fatalf("launcher is not executable in archive: %v", mode)
	}
	manifestBytes, _ := readArchiveEntry(t, output, root+manifestName)
	var manifest offlineManifest
	if err := json.Unmarshal(manifestBytes, &manifest); err != nil {
		t.Fatal(err)
	}
	if manifest.Package.Commit != testSHA || manifest.Source.RunID != "12345" ||
		manifest.Site.EntryPoint != "site/app/" {
		t.Fatalf("unexpected manifest %#v", manifest)
	}
	checksums, _ := readArchiveEntry(t, output, root+checksumsName)
	if !strings.Contains(string(checksums), "site/app/exact bytes.bin") ||
		strings.Contains(string(checksums), checksumsName) {
		t.Fatalf("unexpected checksums:\n%s", checksums)
	}
	writeTestFile(t, output+".sha256",
		strings.Repeat("0", 64)+"  "+filepath.Base(output)+"\n")
	if err := verifyArchiveCompanion(output); err == nil ||
		!strings.Contains(err.Error(), "does not match") {
		t.Fatalf("expected a checksum companion mismatch, got %v", err)
	}
}

func TestBuildRejectsManifestSHAMismatch(t *testing.T) {
	artifact := testArtifact(t)
	wrong := map[string]any{
		"package": map[string]any{
			"name": "OpenSpecy", "version": "1.7.1",
			"commit": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
		},
	}
	writeTestJSON(t, filepath.Join(artifact, "_site", "app",
		"pinned-wasm-library.json"), wrong)
	launcher := filepath.Join(t.TempDir(), "launcher")
	writeLauncherFixture(t, launcher, "linux-amd64")
	output := filepath.Join(t.TempDir(),
		"openspecy-offline-linux-amd64-"+testSHA+".zip")
	_, err := Build(Config{
		ArtifactRoot: artifact, Launcher: launcher, Output: output,
		PackageSHA: testSHA, Target: "linux-amd64",
		SourceRepository: "example/OpenSpecy-package", SourceRunID: "12345",
	})
	if err == nil || !strings.Contains(err.Error(), "package identity") {
		t.Fatalf("expected identity mismatch, got %v", err)
	}
}

func TestBuildRequiresStableArchiveName(t *testing.T) {
	launcher := filepath.Join(t.TempDir(), "launcher")
	writeLauncherFixture(t, launcher, "windows-amd64")
	_, err := validateConfig(Config{
		ArtifactRoot: "artifact", Launcher: launcher,
		Output: filepath.Join(t.TempDir(), "unexpected.zip"),
		PackageSHA: testSHA, Target: "windows-amd64",
		SourceRepository: "example/OpenSpecy-package", SourceRunID: "12345",
	})
	if err == nil || !strings.Contains(err.Error(), "archive must be named") {
		t.Fatalf("expected stable-name error, got %v", err)
	}
}

func TestValidateLauncherBinaryAcceptsEveryTargetABI(t *testing.T) {
	for _, target := range []string{
		"windows-amd64", "macos-amd64", "macos-arm64",
		"linux-amd64", "linux-arm64",
	} {
		t.Run(target, func(t *testing.T) {
			launcher := filepath.Join(t.TempDir(), "launcher")
			writeLauncherFixture(t, launcher, target)
			if err := validateLauncherBinary(launcher, targets[target]); err != nil {
				t.Fatalf("valid %s launcher was rejected: %v", target, err)
			}
		})
	}
}

func TestValidateLauncherBinaryRejectsWrongArchitecture(t *testing.T) {
	launcher := filepath.Join(t.TempDir(), "launcher")
	writeLauncherFixture(t, launcher, "linux-amd64")
	err := validateLauncherBinary(launcher, targets["linux-arm64"])
	if err == nil || !strings.Contains(err.Error(), "target requires") {
		t.Fatalf("expected launcher architecture mismatch, got %v", err)
	}
}

func TestValidatePortableRelativePath(t *testing.T) {
	for _, name := range []string{
		"site/app/index.html", "site/app/exact bytes.bin", "OpenSpecy-offline-a",
	} {
		if err := validatePortableRelativePath(name); err != nil {
			t.Errorf("valid portable path %q was rejected: %v", name, err)
		}
	}
	for _, name := range []string{
		"../escape", "site/../escape", "/absolute", "C:/absolute",
		"C:relative", `site\app\index.html`, "site//app", "./site",
		"site/app/", "site/app\nindex.html", "site/CON.txt", "site/file.",
		"site/file:name",
	} {
		if err := validatePortableRelativePath(name); err == nil {
			t.Errorf("unsafe portable path %q was accepted", name)
		}
	}
}

func TestVerifyArchiveRejectsDuplicatePortablePaths(t *testing.T) {
	for _, names := range [][]string{
		{"OpenSpecy-offline-" + testSHA + "/site/index.html",
			"OpenSpecy-offline-" + testSHA + "/site/index.html"},
		{"OpenSpecy-offline-" + testSHA + "/site/index.html",
			"OpenSpecy-offline-" + testSHA + "/site/INDEX.html"},
	} {
		archive := filepath.Join(t.TempDir(), "duplicate.zip")
		output, err := os.Create(archive)
		if err != nil {
			t.Fatal(err)
		}
		writer := zip.NewWriter(output)
		for _, name := range names {
			entry, err := writer.Create(name)
			if err != nil {
				t.Fatal(err)
			}
			if _, err := entry.Write([]byte("content")); err != nil {
				t.Fatal(err)
			}
		}
		if err := writer.Close(); err != nil {
			t.Fatal(err)
		}
		if err := output.Close(); err != nil {
			t.Fatal(err)
		}
		err = verifyArchive(archive, "OpenSpecy-offline-"+testSHA,
			testSHA, "linux-amd64", "OpenSpecy Offline")
		if err == nil || !strings.Contains(err.Error(), "duplicate or colliding") {
			t.Fatalf("expected duplicate portable path rejection, got %v", err)
		}
	}
}

func TestParseChecksumsRejectsUnsafeAndCollidingPaths(t *testing.T) {
	hash := strings.Repeat("a", 64)
	for _, content := range []string{
		hash + `  site\app\index.html` + "\n",
		hash + "  C:/index.html\n",
		hash + "  site/index.html\n" + hash + "  site/INDEX.html\n",
	} {
		if _, err := parseChecksums([]byte(content)); err == nil {
			t.Fatalf("unsafe checksum paths were accepted: %q", content)
		}
	}
}
