# Workflow derived from https://github.com/r-wasm/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  release:
    # Must republish release to update assets
    types: [ published ]

name: Build and deploy wasm R package image

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.2' # Adjust the version as needed

      # Install additional R packages if required
      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("pak"))' # Add more dependencies if needed
  release-file-system-image:
    uses: r-wasm/actions/.github/workflows/release-file-system-image.yml@v2
    permissions:
      # For publishing artifact files to the release
      contents: write
      # To download GitHub Packages within action
      repository-projects: read


